import type { PlanDefinition } from '../types/subscriptionTypes';

export const PLAN_CATALOG: Record<PlanDefinition['id'], PlanDefinition> = {
  basic: {
    id: 'basic',
    displayName: 'Basic',
    rank: 1,
    entitlements: {
      featureFlags: {
        canUsePOS: false,
        canExportReports: false,
        canManageProducts: true,
        canUseOfflineMode: false,
        canViewAuditLogs: false,
        canManageUsers: false,
        canUseMultiBranch: false,
        canManageSuppliers: false,
        canManageCustomers: false,
        canManagePurchaseOrders: false,
        canUseAdvancedAnalytics: false,
        canAccessAPI: false,
        canUseCustomBranding: false,
        canUseSmsNotifications: false,
        canUseBatchOperations: false,
      },
      limits: {
        maxUsers: 1,
        maxProducts: 100,
        maxMonthlyTransactions: 0,
        maxBranches: 1,
      },
    },
  },
  standard: {
    id: 'standard',
    displayName: 'Standard',
    rank: 2,
    entitlements: {
      featureFlags: {
        canUsePOS: true,
        canExportReports: true,
        canManageProducts: true,
        canUseOfflineMode: true,
        canViewAuditLogs: true,
        canManageUsers: true,
        canUseMultiBranch: false,
        canManageSuppliers: true,
        canManageCustomers: true,
        canManagePurchaseOrders: true,
        canUseAdvancedAnalytics: false,
        canAccessAPI: false,
        canUseCustomBranding: false,
        canUseSmsNotifications: false,
        canUseBatchOperations: false,
      },
      limits: {
        maxUsers: 3,
        maxProducts: null,
        maxMonthlyTransactions: 10000,
        maxBranches: 1,
      },
    },
  },
  premium: {
    id: 'premium',
    displayName: 'Premium',
    rank: 3,
    entitlements: {
      featureFlags: {
        canUsePOS: true,
        canExportReports: true,
        canManageProducts: true,
        canUseOfflineMode: true,
        canViewAuditLogs: true,
        canManageUsers: true,
        canUseMultiBranch: true,
        canManageSuppliers: true,
        canManageCustomers: true,
        canManagePurchaseOrders: true,
        canUseAdvancedAnalytics: true,
        canAccessAPI: true,
        canUseCustomBranding: true,
        canUseSmsNotifications: true,
        canUseBatchOperations: true,
      },
      limits: {
        maxUsers: null,
        maxProducts: null,
        maxMonthlyTransactions: null,
        maxBranches: null,
      },
    },
  },
  enterprise: {
    id: 'enterprise',
    displayName: 'Enterprise',
    rank: 4,
    entitlements: {
      featureFlags: {
        canUsePOS: true,
        canExportReports: true,
        canManageProducts: true,
        canUseOfflineMode: true,
        canViewAuditLogs: true,
        canManageUsers: true,
        canUseMultiBranch: true,
        canManageSuppliers: true,
        canManageCustomers: true,
        canManagePurchaseOrders: true,
        canUseAdvancedAnalytics: true,
        canAccessAPI: true,
        canUseCustomBranding: true,
        canUseSmsNotifications: true,
        canUseBatchOperations: true,
      },
      limits: {
        maxUsers: null,
        maxProducts: null,
        maxMonthlyTransactions: null,
        maxBranches: null,
      },
    },
  },
};
